### ISSUE TITLE
Installation Error!

### ISSUE THREAD

**Issue by essoojay** [zpoint/wireguard_socks5_docker#1]
Last login: Fri Oct 20 21:46:31 2023 from xx.xx.xx.xx
root@localhost:~# cd wireguard_socks5_docker
root@localhost:~/wireguard_socks5_docker# bash ./build.sh
[+] Building 2.9s (5/7)                                                              docker:default
 => [internal] load build definition from Dockerfile                                           0.0s
 => => transferring dockerfile: 558B                                                           0.0s
 => [internal] load .dockerignore                                                              0.0s
 => => transferring context: 2B                                                                0.0s
 => [internal] load metadata for docker.io/library/debian:stable                               0.3s
 => CACHED [1/4] FROM docker.io/library/debian:stable@sha256:fd865da5f887f2fdb7af19c3a33fe9c9  0.0s
 => ERROR [2/4] RUN apt-get update &&     apt-get install -y     net-tools     wireguard       2.5s
------
 > [2/4] RUN apt-get update &&     apt-get install -y     net-tools     wireguard     dante-server     sudo     iproute2     procps     vim     curl     openresolv     wireguard-dkms     wireguard-tools     &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*:
0.173 Get:1 http://deb.debian.org/debian stable InRelease [151 kB]
0.192 Get:2 http://deb.debian.org/debian stable-updates InRelease [52.1 kB]
0.193 Get:3 http://deb.debian.org/debian-security stable-security InRelease [48.0 kB]
0.233 Get:4 http://deb.debian.org/debian stable/main amd64 Packages [8780 kB]
0.366 Get:5 http://deb.debian.org/debian stable-updates/main amd64 Packages [6408 B]
0.503 Get:6 http://deb.debian.org/debian-security stable-security/main amd64 Packages [86.2 kB]
1.427 Fetched 9124 kB in 1s (7239 kB/s)
1.427 Reading package lists...
1.905 Reading package lists...
2.388 Building dependency tree...
2.487 Reading state information...
2.491 Package wireguard-dkms is not available, but is referred to by another package.
2.491 This may mean that the package is missing, has been obsoleted, or
2.491 is only available from another source
2.491
2.493 E: Package 'wireguard-dkms' has no installation candidate
------
Dockerfile:3
--------------------
   2 |
   3 | >>> RUN apt-get update && \
   4 | >>>     apt-get install -y \
   5 | >>>     net-tools \
   6 | >>>     wireguard \
   7 | >>>     dante-server \
   8 | >>>     sudo \
   9 | >>>     iproute2 \
  10 | >>>     procps \
  11 | >>>     vim \
  12 | >>>     curl \
  13 | >>>     openresolv \
  14 | >>>     wireguard-dkms \
  15 | >>>     wireguard-tools \
  16 | >>>     && \
  17 | >>>     apt-get clean && \
  18 | >>>     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  19 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y     net-tools     wireguard     dante-server     sudo     iproute2     procps     vim     curl     openresolv     wireguard-dkms     wireguard-tools     &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*" did not complete successfully: exit code: 100
root@localhost:~/wireguard_socks5_docker#

**Comment by zpoint** [comment]
The latest `debian` version does not support this install command anymore, I've updated the `Dockerfile` to use specific debian version, please pull the latest code and run again
